name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Convert markdown posts
        run: npx tsx server/convert-posts.ts

      - name: Generate static pages
        run: |
          npx tsx server/convert-pages.ts
          echo "Generated files in dist/public:"
          ls -la dist/public/

      - name: Build client only
        run: npm exec -- vite build

      - name: Copy 404.html
        run: cp client/public/404.html ./dist/public/404.html

      - name: Add CNAME file
        run: echo "algorhythmandflow.com" > ./dist/public/CNAME

      - name: List final files
        run: |
          echo "Final files to be deployed:"
          ls -la ./dist/public/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/public
          branch: gh-pages