name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Change to your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        
      - name: Generate Blog Posts
        run: npm run generate-blog

      - name: Build client only
        run: npm run build:client

      - name: Add CNAME file
        run: echo "algorhythmandflow.com" > ./dist/public/CNAME  # Replace with your actual domain name

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/public  # Matches your Vite output directory
          branch: gh-pages

      - name: Debug* List gh-pages branch content AFTER deployment
        run: |
          echo "Contents of gh-pages branch after deployment:"
          git clone --depth 1 --branch gh-pages file://$GITHUB_WORKSPACE gh-pages-content
          ls -al gh-pages-content
          ls -al gh-pages-content/assets # List assets folder content specifically
          rm -rf gh-pages-content # Clean up debug clone
